services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: cosmetics-postgres
    environment:
      - POSTGRES_DB=cosmetics_data_hub
      - POSTGRES_USER=cosmetics_user
      - POSTGRES_PASSWORD=cosmetics_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Next.js Application
  app:
    build: .
    container_name: cosmetics-app
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://cosmetics_user:cosmetics_password@postgres:5432/cosmetics_data_hub?sslmode=disable
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
